#!/usr/bin/env python
# encoding: utf-8
"""
@Company：华中科技大学电气学院聚变与等离子研究所
@version: V1.0
@author: Victor
@contact: 1650996069@qq.com or yexin@hust.edu.cn 2018--2020
@software: PyCharm
@file: Two_Sum.py
@time: 2019/2/18 21:13
@Desc：Given an array of integers,
       return indices of the two numbers such that they add up to a specific target.

       Example:

            Given nums = [2, 7, 11, 15], target = 9,

            Because nums[0] + nums[1] = 2 + 7 = 9,
            return [0, 1].

"""
nums = [2,3,6,9,7,8]

def towsum(nums,target):
    dic = dict()
    k = 0
    for  i in range(len(nums)-1):
        for j in range(i+1,len(nums)):
            if nums[i]+nums[j] == target:
                k += 1
                dic[k] = [i,j]
    return dic

print(towsum(nums,9))
